// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANUJRVCvBLFiWtJSqP6NS7wVZuSINySik',
    appId: '1:339794104760:web:66f81a1213168e1b1bbf4d',
    messagingSenderId: '339794104760',
    projectId: 'airguardfire',
    authDomain: 'airguardfire.firebaseapp.com',
    databaseURL: 'https://airguardfire-default-rtdb.firebaseio.com',
    storageBucket: 'airguardfire.firebasestorage.app',
    measurementId: 'G-XHLENGGHL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3iObK4JTysERoYKUXzQgPoXCqeW0VG1A',
    appId: '1:339794104760:android:8853b9c09e0d0b7a1bbf4d',
    messagingSenderId: '339794104760',
    projectId: 'airguardfire',
    databaseURL: 'https://airguardfire-default-rtdb.firebaseio.com',
    storageBucket: 'airguardfire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcEG8xbOHiY-7V7APnShRqAQJoEzDaCIY',
    appId: '1:339794104760:ios:e5c2ba816967b2011bbf4d',
    messagingSenderId: '339794104760',
    projectId: 'airguardfire',
    databaseURL: 'https://airguardfire-default-rtdb.firebaseio.com',
    storageBucket: 'airguardfire.firebasestorage.app',
    iosClientId: '339794104760-037pst9rdifdll2lgm08al3jpfm4qpub.apps.googleusercontent.com',
    iosBundleId: 'com.example.airGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcEG8xbOHiY-7V7APnShRqAQJoEzDaCIY',
    appId: '1:339794104760:ios:e5c2ba816967b2011bbf4d',
    messagingSenderId: '339794104760',
    projectId: 'airguardfire',
    databaseURL: 'https://airguardfire-default-rtdb.firebaseio.com',
    storageBucket: 'airguardfire.firebasestorage.app',
    iosClientId: '339794104760-037pst9rdifdll2lgm08al3jpfm4qpub.apps.googleusercontent.com',
    iosBundleId: 'com.example.airGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANUJRVCvBLFiWtJSqP6NS7wVZuSINySik',
    appId: '1:339794104760:web:d226e8bf86bbb3771bbf4d',
    messagingSenderId: '339794104760',
    projectId: 'airguardfire',
    authDomain: 'airguardfire.firebaseapp.com',
    databaseURL: 'https://airguardfire-default-rtdb.firebaseio.com',
    storageBucket: 'airguardfire.firebasestorage.app',
    measurementId: 'G-JNTW137YBR',
  );

}